#pragma once

#define LAB_VERSION_MAJOR 0
#define LAB_VERSION_MINOR 0
#define LAB_VERSION_PATCH 1
#define LAB_VERSION               \
  LAB_MAKE_STR(LAB_VERSION_MAJOR) \
  "." LAB_MAKE_STR(LAB_VERSION_MINOR) "." LAB_MAKE_STR(LAB_VERSION_PATCH)