#pragma once

#define RENDERER_VERSION_MAJOR 0
#define RENDERER_VERSION_MINOR 0
#define RENDERER_VERSION_PATCH 1
#define RENDERER_VERSION RENDERER_MAKE_STR(RENDERER_VERSION_MAJOR) "." RENDERER_MAKE_STR(RENDERER_VERSION_MINOR) "." RENDERER_MAKE_STR(RENDERER_VERSION_PATCH)